name: native_toolchain_zig
description: >
  Zig support for Dart's build hooks.
  Automatically builds and bundles your Zig code with your Dart/Flutter application.
version: 0.1.0
homepage: https://github.com/ykmnkmi/native_toolchain_zig.dart
repository: https://github.com/ykmnkmi/native_toolchain_zig.dart
issue_tracker: https://github.com/ykmnkmi/native_toolchain_zig.dart/issues

environment:
  sdk: ^3.11.0

workspace:
  - example/zig_math
  - example/zig_dart_api
  - example/zig_tcp

topics:
  - zig
  - ffi
  - interop
  - native-assets
  - native-toolchain

dependencies:
  code_assets: ^1.0.0
  ffi: ^2.2.0
  hooks: ^1.0.1
  logging: ^1.3.0
  meta: ^1.18.1
  path: ^1.9.1

dev_dependencies:
  lints: ^6.1.0
  test: ^1.29.0
