name: zig_tcp
description: Example demonstrating native_toolchain_zig usage.
version: 0.1.0

publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  ffi: ^2.1.5
  hooks: ^1.0.0
  logging: ^1.3.0
  meta: ^1.18.1
  native_toolchain_zig: ^0.1.0

dev_dependencies:
  lints: ^6.0.0
