name: zig_dart_api
description: Example demonstrating native_toolchain_zig usage.
version: 0.1.0

publish_to: none

environment:
  sdk: ^3.10.8

resolution: workspace

dependencies:
  hooks: ^1.0.1
  logging: ^1.3.0
  native_toolchain_zig: ^0.1.0

dev_dependencies:
  lints: ^6.1.0
